// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pg.employee.grpcjava.api;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IBackendGRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.IBackendGRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string error = 1;</code>
     * @return A list containing the error.
     */
    java.util.List<String>
        getErrorList();
    /**
     * <code>repeated string error = 1;</code>
     * @return The count of error.
     */
    int getErrorCount();
    /**
     * <code>repeated string error = 1;</code>
     * @param index The index of the element to return.
     * @return The error at the given index.
     */
    String getError(int index);
    /**
     * <code>repeated string error = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the error at the given index.
     */
    com.google.protobuf.ByteString
        getErrorBytes(int index);

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>bool status = 3;</code>
     * @return The status.
     */
    boolean getStatus();

    /**
     * <code>string data = 4;</code>
     * @return The data.
     */
    String getData();
    /**
     * <code>string data = 4;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>int32 code = 5;</code>
     * @return The code.
     */
    int getCode();
  }
  /**
   * Protobuf type {@code api.IBackendGRPC}
   */
  public static final class IBackendGRPC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.IBackendGRPC)
      IBackendGRPCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IBackendGRPC.newBuilder() to construct.
    private IBackendGRPC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IBackendGRPC() {
      error_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      message_ = "";
      data_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new IBackendGRPC();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_api_IBackendGRPC_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_api_IBackendGRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IBackendGRPC.class, Builder.class);
    }

    public static final int ERROR_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList error_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string error = 1;</code>
     * @return A list containing the error.
     */
    public com.google.protobuf.ProtocolStringList
        getErrorList() {
      return error_;
    }
    /**
     * <code>repeated string error = 1;</code>
     * @return The count of error.
     */
    public int getErrorCount() {
      return error_.size();
    }
    /**
     * <code>repeated string error = 1;</code>
     * @param index The index of the element to return.
     * @return The error at the given index.
     */
    public String getError(int index) {
      return error_.get(index);
    }
    /**
     * <code>repeated string error = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the error at the given index.
     */
    public com.google.protobuf.ByteString
        getErrorBytes(int index) {
      return error_.getByteString(index);
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private boolean status_ = false;
    /**
     * <code>bool status = 3;</code>
     * @return The status.
     */
    @Override
    public boolean getStatus() {
      return status_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object data_ = "";
    /**
     * <code>string data = 4;</code>
     * @return The data.
     */
    @Override
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 4;</code>
     * @return The bytes for data.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 5;
    private int code_ = 0;
    /**
     * <code>int32 code = 5;</code>
     * @return The code.
     */
    @Override
    public int getCode() {
      return code_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < error_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, error_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (status_ != false) {
        output.writeBool(3, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, data_);
      }
      if (code_ != 0) {
        output.writeInt32(5, code_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < error_.size(); i++) {
          dataSize += computeStringSizeNoTag(error_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getErrorList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (status_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, data_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, code_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IBackendGRPC)) {
        return super.equals(obj);
      }
      IBackendGRPC other = (IBackendGRPC) obj;

      if (!getErrorList()
          .equals(other.getErrorList())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getErrorCount() > 0) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getErrorList().hashCode();
      }
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatus());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IBackendGRPC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IBackendGRPC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IBackendGRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IBackendGRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IBackendGRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IBackendGRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IBackendGRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IBackendGRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static IBackendGRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static IBackendGRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IBackendGRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IBackendGRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IBackendGRPC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.IBackendGRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.IBackendGRPC)
        IBackendGRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Api.internal_static_api_IBackendGRPC_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Api.internal_static_api_IBackendGRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IBackendGRPC.class, Builder.class);
      }

      // Construct using api.Api.IBackendGRPC.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        error_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        message_ = "";
        status_ = false;
        data_ = "";
        code_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Api.internal_static_api_IBackendGRPC_descriptor;
      }

      @Override
      public IBackendGRPC getDefaultInstanceForType() {
        return IBackendGRPC.getDefaultInstance();
      }

      @Override
      public IBackendGRPC build() {
        IBackendGRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public IBackendGRPC buildPartial() {
        IBackendGRPC result = new IBackendGRPC(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(IBackendGRPC result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          error_.makeImmutable();
          result.error_ = error_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.code_ = code_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IBackendGRPC) {
          return mergeFrom((IBackendGRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IBackendGRPC other) {
        if (other == IBackendGRPC.getDefaultInstance()) return this;
        if (!other.error_.isEmpty()) {
          if (error_.isEmpty()) {
            error_ = other.error_;
            bitField0_ |= 0x00000001;
          } else {
            ensureErrorIsMutable();
            error_.addAll(other.error_);
          }
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getStatus() != false) {
          setStatus(other.getStatus());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                String s = input.readStringRequireUtf8();
                ensureErrorIsMutable();
                error_.add(s);
                break;
              } // case 10
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                status_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                data_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList error_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureErrorIsMutable() {
        if (!error_.isModifiable()) {
          error_ = new com.google.protobuf.LazyStringArrayList(error_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string error = 1;</code>
       * @return A list containing the error.
       */
      public com.google.protobuf.ProtocolStringList
          getErrorList() {
        error_.makeImmutable();
        return error_;
      }
      /**
       * <code>repeated string error = 1;</code>
       * @return The count of error.
       */
      public int getErrorCount() {
        return error_.size();
      }
      /**
       * <code>repeated string error = 1;</code>
       * @param index The index of the element to return.
       * @return The error at the given index.
       */
      public String getError(int index) {
        return error_.get(index);
      }
      /**
       * <code>repeated string error = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the error at the given index.
       */
      public com.google.protobuf.ByteString
          getErrorBytes(int index) {
        return error_.getByteString(index);
      }
      /**
       * <code>repeated string error = 1;</code>
       * @param index The index to set the value at.
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureErrorIsMutable();
        error_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string error = 1;</code>
       * @param value The error to add.
       * @return This builder for chaining.
       */
      public Builder addError(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureErrorIsMutable();
        error_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string error = 1;</code>
       * @param values The error to add.
       * @return This builder for chaining.
       */
      public Builder addAllError(
          Iterable<String> values) {
        ensureErrorIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, error_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string error = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        error_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string error = 1;</code>
       * @param value The bytes of the error to add.
       * @return This builder for chaining.
       */
      public Builder addErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureErrorIsMutable();
        error_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean status_ ;
      /**
       * <code>bool status = 3;</code>
       * @return The status.
       */
      @Override
      public boolean getStatus() {
        return status_;
      }
      /**
       * <code>bool status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(boolean value) {

        status_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = false;
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <code>string data = 4;</code>
       * @return The data.
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string data = 4;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = getDefaultInstance().getData();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string data = 4;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        data_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 5;</code>
       * @return The code.
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 5;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        code_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.IBackendGRPC)
    }

    // @@protoc_insertion_point(class_scope:api.IBackendGRPC)
    private static final IBackendGRPC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IBackendGRPC();
    }

    public static IBackendGRPC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IBackendGRPC>
        PARSER = new com.google.protobuf.AbstractParser<IBackendGRPC>() {
      @Override
      public IBackendGRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IBackendGRPC> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IBackendGRPC> getParserForType() {
      return PARSER;
    }

    @Override
    public IBackendGRPC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.Meta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 current = 1;</code>
     * @return The current.
     */
    int getCurrent();

    /**
     * <code>int32 pageSize = 2;</code>
     * @return The pageSize.
     */
    int getPageSize();

    /**
     * <code>int32 totalPage = 3;</code>
     * @return The totalPage.
     */
    int getTotalPage();

    /**
     * <code>int32 totalItem = 4;</code>
     * @return The totalItem.
     */
    int getTotalItem();
  }
  /**
   * Protobuf type {@code api.Meta}
   */
  public static final class Meta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.Meta)
      MetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Meta.newBuilder() to construct.
    private Meta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Meta() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Meta();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_api_Meta_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_api_Meta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Meta.class, Builder.class);
    }

    public static final int CURRENT_FIELD_NUMBER = 1;
    private int current_ = 0;
    /**
     * <code>int32 current = 1;</code>
     * @return The current.
     */
    @Override
    public int getCurrent() {
      return current_;
    }

    public static final int PAGESIZE_FIELD_NUMBER = 2;
    private int pageSize_ = 0;
    /**
     * <code>int32 pageSize = 2;</code>
     * @return The pageSize.
     */
    @Override
    public int getPageSize() {
      return pageSize_;
    }

    public static final int TOTALPAGE_FIELD_NUMBER = 3;
    private int totalPage_ = 0;
    /**
     * <code>int32 totalPage = 3;</code>
     * @return The totalPage.
     */
    @Override
    public int getTotalPage() {
      return totalPage_;
    }

    public static final int TOTALITEM_FIELD_NUMBER = 4;
    private int totalItem_ = 0;
    /**
     * <code>int32 totalItem = 4;</code>
     * @return The totalItem.
     */
    @Override
    public int getTotalItem() {
      return totalItem_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (current_ != 0) {
        output.writeInt32(1, current_);
      }
      if (pageSize_ != 0) {
        output.writeInt32(2, pageSize_);
      }
      if (totalPage_ != 0) {
        output.writeInt32(3, totalPage_);
      }
      if (totalItem_ != 0) {
        output.writeInt32(4, totalItem_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (current_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, current_);
      }
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageSize_);
      }
      if (totalPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalPage_);
      }
      if (totalItem_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalItem_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Meta)) {
        return super.equals(obj);
      }
      Meta other = (Meta) obj;

      if (getCurrent()
          != other.getCurrent()) return false;
      if (getPageSize()
          != other.getPageSize()) return false;
      if (getTotalPage()
          != other.getTotalPage()) return false;
      if (getTotalItem()
          != other.getTotalItem()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrent();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (37 * hash) + TOTALPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPage();
      hash = (37 * hash) + TOTALITEM_FIELD_NUMBER;
      hash = (53 * hash) + getTotalItem();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Meta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Meta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Meta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Meta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Meta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Meta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Meta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Meta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Meta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Meta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Meta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Meta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Meta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.Meta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.Meta)
        MetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Api.internal_static_api_Meta_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Api.internal_static_api_Meta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Meta.class, Builder.class);
      }

      // Construct using api.Api.Meta.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        current_ = 0;
        pageSize_ = 0;
        totalPage_ = 0;
        totalItem_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Api.internal_static_api_Meta_descriptor;
      }

      @Override
      public Meta getDefaultInstanceForType() {
        return Meta.getDefaultInstance();
      }

      @Override
      public Meta build() {
        Meta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Meta buildPartial() {
        Meta result = new Meta(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Meta result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.current_ = current_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pageSize_ = pageSize_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalPage_ = totalPage_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.totalItem_ = totalItem_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Meta) {
          return mergeFrom((Meta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Meta other) {
        if (other == Meta.getDefaultInstance()) return this;
        if (other.getCurrent() != 0) {
          setCurrent(other.getCurrent());
        }
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        if (other.getTotalPage() != 0) {
          setTotalPage(other.getTotalPage());
        }
        if (other.getTotalItem() != 0) {
          setTotalItem(other.getTotalItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                current_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                pageSize_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                totalPage_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                totalItem_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int current_ ;
      /**
       * <code>int32 current = 1;</code>
       * @return The current.
       */
      @Override
      public int getCurrent() {
        return current_;
      }
      /**
       * <code>int32 current = 1;</code>
       * @param value The current to set.
       * @return This builder for chaining.
       */
      public Builder setCurrent(int value) {

        current_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 current = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        current_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <code>int32 pageSize = 2;</code>
       * @return The pageSize.
       */
      @Override
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>int32 pageSize = 2;</code>
       * @param value The pageSize to set.
       * @return This builder for chaining.
       */
      public Builder setPageSize(int value) {

        pageSize_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pageSize = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageSize_ = 0;
        onChanged();
        return this;
      }

      private int totalPage_ ;
      /**
       * <code>int32 totalPage = 3;</code>
       * @return The totalPage.
       */
      @Override
      public int getTotalPage() {
        return totalPage_;
      }
      /**
       * <code>int32 totalPage = 3;</code>
       * @param value The totalPage to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPage(int value) {

        totalPage_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalPage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalPage_ = 0;
        onChanged();
        return this;
      }

      private int totalItem_ ;
      /**
       * <code>int32 totalItem = 4;</code>
       * @return The totalItem.
       */
      @Override
      public int getTotalItem() {
        return totalItem_;
      }
      /**
       * <code>int32 totalItem = 4;</code>
       * @param value The totalItem to set.
       * @return This builder for chaining.
       */
      public Builder setTotalItem(int value) {

        totalItem_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalItem = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalItem() {
        bitField0_ = (bitField0_ & ~0x00000008);
        totalItem_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.Meta)
    }

    // @@protoc_insertion_point(class_scope:api.Meta)
    private static final Meta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Meta();
    }

    public static Meta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Meta>
        PARSER = new com.google.protobuf.AbstractParser<Meta>() {
      @Override
      public Meta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Meta> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Meta> getParserForType() {
      return PARSER;
    }

    @Override
    public Meta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IModelPaginateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.IModelPaginate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.api.Meta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    boolean hasMeta();
    /**
     * <code>.api.Meta meta = 1;</code>
     * @return The meta.
     */
    Meta getMeta();
    /**
     * <code>.api.Meta meta = 1;</code>
     */
    MetaOrBuilder getMetaOrBuilder();

    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getResultList();
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    com.google.protobuf.Any getResult(int index);
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getResultOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code api.IModelPaginate}
   */
  public static final class IModelPaginate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.IModelPaginate)
      IModelPaginateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IModelPaginate.newBuilder() to construct.
    private IModelPaginate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IModelPaginate() {
      result_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new IModelPaginate();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_api_IModelPaginate_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_api_IModelPaginate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IModelPaginate.class, Builder.class);
    }

    public static final int META_FIELD_NUMBER = 1;
    private Meta meta_;
    /**
     * <code>.api.Meta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    @Override
    public boolean hasMeta() {
      return meta_ != null;
    }
    /**
     * <code>.api.Meta meta = 1;</code>
     * @return The meta.
     */
    @Override
    public Meta getMeta() {
      return meta_ == null ? Meta.getDefaultInstance() : meta_;
    }
    /**
     * <code>.api.Meta meta = 1;</code>
     */
    @Override
    public MetaOrBuilder getMetaOrBuilder() {
      return meta_ == null ? Meta.getDefaultInstance() : meta_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.Any> result_;
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    @Override
    public java.util.List<com.google.protobuf.Any> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    @Override
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    @Override
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    @Override
    public com.google.protobuf.Any getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any result = 2;</code>
     */
    @Override
    public com.google.protobuf.AnyOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (meta_ != null) {
        output.writeMessage(1, getMeta());
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(2, result_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeta());
      }
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, result_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IModelPaginate)) {
        return super.equals(obj);
      }
      IModelPaginate other = (IModelPaginate) obj;

      if (hasMeta() != other.hasMeta()) return false;
      if (hasMeta()) {
        if (!getMeta()
            .equals(other.getMeta())) return false;
      }
      if (!getResultList()
          .equals(other.getResultList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IModelPaginate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IModelPaginate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IModelPaginate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IModelPaginate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IModelPaginate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IModelPaginate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IModelPaginate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IModelPaginate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static IModelPaginate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static IModelPaginate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IModelPaginate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IModelPaginate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IModelPaginate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.IModelPaginate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.IModelPaginate)
        IModelPaginateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Api.internal_static_api_IModelPaginate_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Api.internal_static_api_IModelPaginate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IModelPaginate.class, Builder.class);
      }

      // Construct using api.Api.IModelPaginate.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        meta_ = null;
        if (metaBuilder_ != null) {
          metaBuilder_.dispose();
          metaBuilder_ = null;
        }
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
        } else {
          result_ = null;
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Api.internal_static_api_IModelPaginate_descriptor;
      }

      @Override
      public IModelPaginate getDefaultInstanceForType() {
        return IModelPaginate.getDefaultInstance();
      }

      @Override
      public IModelPaginate build() {
        IModelPaginate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public IModelPaginate buildPartial() {
        IModelPaginate result = new IModelPaginate(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(IModelPaginate result) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
      }

      private void buildPartial0(IModelPaginate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.meta_ = metaBuilder_ == null
              ? meta_
              : metaBuilder_.build();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IModelPaginate) {
          return mergeFrom((IModelPaginate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IModelPaginate other) {
        if (other == IModelPaginate.getDefaultInstance()) return this;
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMetaFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.Any m =
                    input.readMessage(
                        com.google.protobuf.Any.parser(),
                        extensionRegistry);
                if (resultBuilder_ == null) {
                  ensureResultIsMutable();
                  result_.add(m);
                } else {
                  resultBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Meta meta_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Meta, Meta.Builder, MetaOrBuilder> metaBuilder_;
      /**
       * <code>.api.Meta meta = 1;</code>
       * @return Whether the meta field is set.
       */
      public boolean hasMeta() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.api.Meta meta = 1;</code>
       * @return The meta.
       */
      public Meta getMeta() {
        if (metaBuilder_ == null) {
          return meta_ == null ? Meta.getDefaultInstance() : meta_;
        } else {
          return metaBuilder_.getMessage();
        }
      }
      /**
       * <code>.api.Meta meta = 1;</code>
       */
      public Builder setMeta(Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          meta_ = value;
        } else {
          metaBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.Meta meta = 1;</code>
       */
      public Builder setMeta(
          Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          meta_ = builderForValue.build();
        } else {
          metaBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.Meta meta = 1;</code>
       */
      public Builder mergeMeta(Meta value) {
        if (metaBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            meta_ != null &&
            meta_ != Meta.getDefaultInstance()) {
            getMetaBuilder().mergeFrom(value);
          } else {
            meta_ = value;
          }
        } else {
          metaBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.Meta meta = 1;</code>
       */
      public Builder clearMeta() {
        bitField0_ = (bitField0_ & ~0x00000001);
        meta_ = null;
        if (metaBuilder_ != null) {
          metaBuilder_.dispose();
          metaBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.api.Meta meta = 1;</code>
       */
      public Meta.Builder getMetaBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.api.Meta meta = 1;</code>
       */
      public MetaOrBuilder getMetaOrBuilder() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilder();
        } else {
          return meta_ == null ?
              Meta.getDefaultInstance() : meta_;
        }
      }
      /**
       * <code>.api.Meta meta = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Meta, Meta.Builder, MetaOrBuilder>
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Meta, Meta.Builder, MetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }

      private java.util.List<com.google.protobuf.Any> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          result_ = new java.util.ArrayList<com.google.protobuf.Any>(result_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> resultBuilder_;

      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public java.util.List<com.google.protobuf.Any> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public com.google.protobuf.Any getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder setResult(
          int index, com.google.protobuf.Any value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder setResult(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder addResult(com.google.protobuf.Any value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder addResult(
          int index, com.google.protobuf.Any value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder addResult(
          com.google.protobuf.Any.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder addResult(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder addAllResult(
          Iterable<? extends com.google.protobuf.Any> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public com.google.protobuf.Any.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public com.google.protobuf.Any.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public com.google.protobuf.Any.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any result = 2;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.IModelPaginate)
    }

    // @@protoc_insertion_point(class_scope:api.IModelPaginate)
    private static final IModelPaginate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IModelPaginate();
    }

    public static IModelPaginate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IModelPaginate>
        PARSER = new com.google.protobuf.AbstractParser<IModelPaginate>() {
      @Override
      public IModelPaginate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IModelPaginate> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IModelPaginate> getParserForType() {
      return PARSER;
    }

    @Override
    public IModelPaginate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_IBackendGRPC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_IBackendGRPC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Meta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Meta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_IModelPaginate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_IModelPaginate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tapi.proto\022\003api\032\031google/protobuf/any.pr" +
      "oto\"Z\n\014IBackendGRPC\022\r\n\005error\030\001 \003(\t\022\017\n\007me" +
      "ssage\030\002 \001(\t\022\016\n\006status\030\003 \001(\010\022\014\n\004data\030\004 \001(" +
      "\t\022\014\n\004code\030\005 \001(\005\"O\n\004Meta\022\017\n\007current\030\001 \001(\005" +
      "\022\020\n\010pageSize\030\002 \001(\005\022\021\n\ttotalPage\030\003 \001(\005\022\021\n" +
      "\ttotalItem\030\004 \001(\005\"O\n\016IModelPaginate\022\027\n\004me" +
      "ta\030\001 \001(\0132\t.api.Meta\022$\n\006result\030\002 \003(\0132\024.go" +
      "ogle.protobuf.Anyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_api_IBackendGRPC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_IBackendGRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_IBackendGRPC_descriptor,
        new String[] { "Error", "Message", "Status", "Data", "Code", });
    internal_static_api_Meta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Meta_descriptor,
        new String[] { "Current", "PageSize", "TotalPage", "TotalItem", });
    internal_static_api_IModelPaginate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_IModelPaginate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_IModelPaginate_descriptor,
        new String[] { "Meta", "Result", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
